name: Upload Website to CPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to FTP
        uses: SebastianRiedel/ftp-action@v1.0.0
        with:
          host: "${{ secrets.FTP_SERVER }}"
          user: "${{ secrets.FTP_USERNAME }}"
          password: "${{ secrets.FTP_PASSWORD }}"
          localDir: "./"
          remoteDir: "wedding.abadeolu.com"
