name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: FTP Deploy (Full Upload)
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: "${{ secrets.FTP_SERVER }}"
          ftp-username: "${{ secrets.FTP_USERNAME }}"
          ftp-password: "${{ secrets.FTP_PASSWORD }}"
          git-ftp-args: --auto-init  # <-- force full upload, skip git diff issues
